Epinar 3
flerdacodeu/CodeU-2018-Group2 pull request #20
Opened 2018-06-19 09:52 UTC by epinar

- There is a referenced "isVisited" array problem. How can we send a copy at each recursive call?
- Should we solve this by yielding? -> But then, how will we able to search "CARD" after finding the word "CAR"?

2018-06-21 15:19 UTC, jdb requested changes

2018-06-21 15:19 UTC, jdb commented on epinar/assignment3/word_search.py
> +		:param words: Valid entries in a dictionary.
can you use the Python type annotations instead of these syntax for the function signature?

https://docs.python.org/3/library/typing.html

2018-06-21 15:19 UTC, jdb commented on epinar/assignment3/word_search.py
> +			visited_cache = [[False for _ in range(N)] for _ in range(M)]
visited_cache = [[False] * N] for _ in range(M)]
Yes, in Python, the list can be multiplied: the new list has the *same elements* repeated, many references to the same object instance.

See the emphasis on *same* above? If the element is immutable like False, it is ok to have many references toward it, but if the element is mutable, this won't work in ourcase, we do not want to have a list of references to the same list of False. A mutation through any reference modifies the list pointed to by all references

>>> [False] * 10
[False, False, False, False, False, False, False, False, False, False]

>>> l = [[1, 2]] * 2
[[1, 2], [1, 2]]

>>> l[0][0] = 9
[[9, 2], [9, 2]]

2018-06-21 15:19 UTC, jdb commented on epinar/assignment3/word_search.py
> +			new_words += _search(grid, dict, "", k, l, visited_cache, [])
found_words.update(_search(grid, dict, "", k, l, visited_cache, []))

2018-06-21 15:43 UTC, jdb commented
Please be more precise, more specific. What do you want to yield exactly?
One way to solve this problem with a generic, methodic way is to think about it as a graph traversal problem: a node is an (i, j) position in the grid, and line of ancestors (a "path") is a prefix.

Then you can solve the problem in 2 steps:
- build the right traversal function
- use the list of elements returned by the traversal to only keep the ones you want

When you traverse a graph, there is usually two things you may want to yield:
1. yield each node
2. yield each path of nodes

In this context, you want 2. and you want to build a function over the traversal that translate a path  into a prefix, and keep the prefix that are word.

If you can do this, then I explain how to implement the "graph pruning" with the heuristics that bad prefix will never becomes words.

2018-06-24 16:48 UTC, jdb requested changes

2018-06-24 16:48 UTC, jdb commented on epinar/assignment3/word_search.py
> +		isVisited[i][j] = True
Try to reset isVisited to False before exiting the function so the slot becomes free to be visited from another neighbor.
The advantage is that you can pass the same mutable state to all recursive call, without copying isVisited at each function call.

2018-06-24 23:59 UTC, epinar commented on epinar/assignment3/word_search.py
> +		isVisited[i][j] = True
I am not sure if I understand your point. I think we can visit each node once, no? So, if we include a letter, it should stay visited. however, in the end, when we return to the search's starting point, we should reset the nodes that weren't included.

2018-06-28 14:30 UTC, jdb requested changes

2018-06-28 14:30 UTC, jdb commented on epinar/assignment3/word_search.py
> +		isVisited[i][j] = True
Can you add the following unit test?

words = ['crash', 'crush']
self.assertEqual(words, word_search(['crash', 'zzuzz'], words))

I think if you do not remove the current letter from Visited on the way up from the recursion, then in the example above, the  r for example is going to be visited, 'crash' will be found, but the r will not be re-used to create 'crush'. Both should be found.

2018-07-02 20:13 UTC, epinar commented
I added the extra unit test and now it works, thanks

2018-07-10 09:12 UTC, jdb approved these changes

2018-07-10 09:14 UTC, merged