A cool solution with user-controlled graph traversal pruning for assignment 3
flerdacodeu/CodeU-2018-Group2 pull request #22
Opened 2018-06-22 12:15 UTC by jdb

2018-06-25 00:23 UTC, evinpinar commented
It's a great solution, thanks!

2018-06-25 05:32 UTC, SilverSolver commented
I'm not sure - where exactly user controls graph traversal pruning? :smiley:

2018-06-25 06:34 UTC, jdb commented
Ok, "pruning" is cutting a whole area of the graph and we do not even look into it. The term is used in gardening as well, for real tree branches.

2018-06-25 06:35 UTC, jdb commented
And in this solution, we have 2 parts: the traversal function that generates all the path and the functions that uses it to filter the path.

2018-06-25 06:37 UTC, jdb commented
A traversal function that be communicated to stop recursing from the outside (from the caller) is what I find interesting

2018-06-25 06:39 UTC, jdb commented
"Pruning a graph traversal can be controlled from the caller" if this is a bit easier to understand.

2018-06-25 06:39 UTC, jdb commented
I hope I am not confusing you too much with yield and all that, maybe I will send you a solution without yield at all.

2018-06-25 06:47 UTC, SilverSolver commented
No problem! I think I've understand the "yield" part here.
Thanks for explanation, it is more clear now what did you mean

2018-06-25 09:17 UTC, SilverSolver commented on jdb/assignment3/wordsearch.py
> +      self.assertIn(word, words)
:slightly_frowning_face: Unittest give the following error:

**FAIL: test_words (wordsearch.TestGrid)
Traceback (most recent call last):
  File "/mnt/FileStorage/Projects_progs/ForVacancies/CodeU-2018-Group2/jdb/assignment3/wordsearch.py", line 138, in test_words
    self.assertIn(word, words)
AssertionError: 'data' not found in {'tad', 'cat', 'tc', 'tar', 'cr', 'act', 'rd', 'rca', 'card', 'ta', 'ar', 'car', 'arc', 'cd', 'cad', 'ad', 'ca', 'at', 'ac'}**

Then if I'm deleting the 'data', it shows the same error for 'rat'. The rest of words are found correctly.
What's wrong? :thinking: 
:slightly_frowning_face: Unittest give the following error:

**FAIL: test_words (wordsearch.TestGrid)
Traceback (most recent call last):
  File "/mnt/FileStorage/Projects_progs/ForVacancies/CodeU-2018-Group2/jdb/assignment3/wordsearch.py", line 138, in test_words
    self.assertIn(word, words)
AssertionError: 'data' not found in {'tad', 'cat', 'tc', 'tar', 'cr', 'act', 'rd', 'rca', 'card', 'ta', 'ar', 'car', 'arc', 'cd', 'cad', 'ad', 'ca', 'at', 'ac'}**

Then if I'm deleting the 'data', it shows the same error for 'rat'. The rest of words are found correctly.
What's wrong? :thinking: Both words 'data' and 'rat' contains diagonal step, but 'rca', for example, contains it too and not causing the error.

2018-06-25 09:19 UTC, SilverSolver requested changes
The last test cause an error

2018-07-11 14:29 UTC, SilverSolver approved these changes

2018-07-11 14:40 UTC, merged