sridha2412-4 q1 done
flerdacodeu/CodeU-2018-Group2 pull request #23
Opened 2018-07-01 15:20 UTC by Sridha2412

2018-07-01 21:13 UTC, jdb commented on sridha2412/assignment4/counting_islands.py
> +    def _get_neighbours(self, x: int, y: int) -> List[Tuple[int, int]]:
To me it looks like get_neighbours could be simplified by merging it with  find_land. Another approach is to merge it  with __init__ and make a set of of all unvisited *land* position. Unvisited can then shrink as you explore each islands.

2018-07-01 21:21 UTC, jdb commented
Excellent! This is clear and simple code. Thanks for making it clear between private and public functions: it was clear to me which were the important functions and which were the helpers.

2 things you can think of:

1. set a docstring to your module that summarizes in plain English your reasoning.

2. have you thought about a simpler function instead of a class. Functions are simpler to read, they usually have one starting point and one exit points. With object oriented programming, it is a bit more complicated which functions is a callback and gets automatically called, and which functions are called by others...

2018-07-02 22:06 UTC, jdb requested changes
Have you thought about turning the input grid into a set of all unvisited position that are on the land?

This way you would not need to keep both visited and the input grid.

2018-07-05 19:29 UTC, Sridha2412 commented
@jdb not sure if this is what you meant by not having to keep both visited and input grid but I am modifying the original grid

2018-07-07 08:27 UTC, jdb approved these changes
I will send my own solution later today I believe. There, I did not modify the input but used a shrinking set of unvisited position.

2018-07-08 12:07 UTC, merged