Sridha2412 1
flerdacodeu/CodeU-2018-Group2 pull request #3
Opened 2018-05-20 16:15 UTC by Sridha2412

2018-05-21 14:08 UTC, jdb requested changes
Very cool, my first CodeU pull request, good job you :)

2018-05-21 14:08 UTC, jdb commented on sridha2412/assignment1/string_anagrams.py
> +    return sorted(str1) == sorted(str2)
I see a duplication of the logic: the same processing is done on str1 and str2, and then below on each of the words of each of the sentence. Do you think you can propose a solution to encapsulate this logic to be able to reuse it?

2018-05-21 14:08 UTC, jdb commented on sridha2412/assignment1/string_anagrams.py
> +def isSentenceAnagram(str1, str2, caseSensitive):
I think a required condition for two sentences to be anagrams is for each of the word in sentence1 to have an anagram word in sentence2. Do you think you can re-use isAnagram() in IsSentenceAnagram?

2018-05-21 14:08 UTC, jdb commented on sridha2412/assignment1/string_anagrams.py
> +# for words
Please remove the "dead" code

2018-05-21 14:08 UTC, jdb commented on sridha2412/assignment1/string_anagrams.py
> +def isAnagram(str1, str2, caseSensitive):
Please check out https://google.github.io/styleguide/pyguide.html#Naming

Python usually do not use a lot the "camel case" convention but instead uses lower case and underscore.

2018-05-21 14:08 UTC, jdb commented on sridha2412/assignment1/string_anagrams.py
> +if isSentenceAnagram(str1, str2, caseSensitive):
Think about using the ternary operator, you would get less duplication
is_it_or_not = '' if isSentenceAnagram(str1, str2, caseSensitive) else 'NOT '
print(...)

2018-05-21 14:08 UTC, jdb commented on sridha2412/assignment1/string_anagrams.py
> +    print("\""+str1+"\" and \""+str2+"\" are anagrams")
No need to the slash: you can alternate the double and single quote: this is quite convenient.

Ex:
print("I'm embedding a single quote without slashes.")

print('What "they" want us to believe is that "we" "landed" on "the moon"')
print('Wake up, ' + "Sheeple !")

2018-05-21 20:19 UTC, Sridha2412 commented on sridha2412/assignment1/string_anagrams.py
> +def isSentenceAnagram(str1, str2, caseSensitive):
I have made all necessary changes. However, I am not sure sentence_anagram(..) is very efficient.

2018-05-26 11:27 UTC, jdb requested changes
Ah, there is an introduction of O(n^2) algorithm over the previous version that was O(n * ln (n)). This is a regression :)

2018-05-26 11:27 UTC, jdb commented on sridha2412/assignment1/string_anagrams.py
> +    for i in range(0, len(str1)):
2 notes: 
- range(0, 10) is equivalent to range(10). When the first element is not set, then its value defaults to zero.
- this is a problematic change: the previous algorithm was O(n * ln (n)) but now it is O(n * m) where n is the number of words in the first sentences and is the number of words in the second sentence.

I suggest you create a function that takes a sentence and returns a structure whose equality method test for anagrams. This function can take the sentence as an input and return a list of occurences count dictionaries. Do not forget to sort the words of the sentence before creating the list.

I will send a solution of anagram today.

2018-05-26 13:48 UTC, jdb approved these changes

2018-05-26 13:55 UTC, merged